version: '3.7'

services:
  ns:
    #image: cznic/knot:latest  # does not support ed448
    build: knot-dns
    volumes:
    - ./keys:/fixed-keys
    - nsa_storage:/storage
    - nsa_rundir:/rundir
    - ./ns/config:/config
    - ./addzones.sh:/root/bin/addzones.sh
    - ./ns/entrypoint.sh:/entrypoint.sh
    - ./acme/keys/:/etc/knot/acme/
    ports:
    - "${IP_NS}:53:53/udp"
    - "${IP_NS}:53:53/tcp"
    environment:
      - ZONE
      - A_RECORD
      - IP_NS
      - IP_MITM
      - IP_A
    command: /entrypoint.sh
    networks:
    - backend
    restart: unless-stopped
  mitm:
    build: mitm
    volumes:
    - ./mitm/:/mitm
    - ./analysis/:/data/
    ports:
    - "${IP_MITM}:53:53/udp"
    - "${IP_MITM}:53:53/tcp"
    environment:
      AUTH_NS_HOST: ns
      AUTH_NS_PORT: 53
      BE_EVIL: $BE_EVIL
    networks:
    - backend
    command: python3 /mitm/mitm.py
    restart: unless-stopped
    init: true

networks:
  backend:

volumes:
  nsa_storage:
  nsa_rundir:
  nsb_storage:
  nsb_rundir:
